### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by daviddanko** [tcheronneau/homers#5]
Hi,

I am having trouble setting up the app. 

Homers is running on my VM with the IP 192.168.0.101. When I visit http://192.168.0.101:8000 I see a "Hello Homers" text. I've added the scrape job for prometheus and after opening http://192.168.0.101:8000/metrics I can only see "# EOF". Obviously the grafana dashboard doesn't show anything. 

I've tried changing the ports and the address in the [server] section of the config file but that doesn't do anything. Could you please help me out?

Thanks in advance.

Below is my config:

```
  homers:
    image: mcth/homers
    container_name: homers
    ports:
      - "8000:8000"
    volumes:
      - ${MONITORING_CONFIG_FOLDER}/homers/config.toml:/app/config.toml
    restart: unless-stopped
    networks:
      - monitoring
``` 

```
[server]
port=8000
address="0.0.0.0"

[sonarr]
address="http://192.168.0.102:30003/"
api_key="xxx"

[tautulli]
address="http://192.168.0.102:30007/"
api_key="xxx"

[radarr]
address="http://192.168.0.102:30004/"
api_key="xxx"

[overseerr]
address="http://192.168.0.103:20001/"
api_key="xxx"
requests=200
``` 

Logs:

$docker logs homers
2024-11-03T08:21:30.815Z WARN  [rocket::launch] Rocket has launched from http://0.0.0.0:8000
